function [Data] = import_NEICQC(filename, fout)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [EVENTCODE,TDETECTLATENCY,TORIGINPDE,MAGPDE,DLATPDE,DLONPDE,DDEPTHPDE,IUSEDPHFINAL,TORIGININITIAL,MAGINITIAL,DLATINITIAL,DLONINITIAL,DDEPTHINITIAL,DERRMAXHKM,DERRMAXZKM,SCHEDULED_ANALYST,ANALYST1STCLAIM,T1STCLAIMED,ANALYSTLASTCLAIM,TLASTUNCLAIM,ANALYSTFIRSTPUB,QUICK,TFIRSTPUB,ANALYST2NDPUB,Q2UIC,TSECONDPUB,SINSTFIR,TFIRSTEXTP,TFIRSTATWC,TFIRSTPTWC,TFIRSTATWCINT,TFIRSTPTWCINT,INSHA,TBECAMERESP,EVENT_DATE_TIME,PREFMAGCURRENT,DLATCURRENT,DLONCURRENT,DDEPTHCURRENT,TORIGINCURRENT,IUSEDPHCURRENT,TFIRSTGLASS,TORIGINFIRST,MAGFIRST,DLATFIRST,DLONFIRST,DDEPTHFIRST,TORIGINAUTO,MAGAUTO,DLATAUTO,DLONAUTO,DDEPTHAUTO,TORIGIN10,MAG10,DLAT10,DLON10,DDEPTH10,IPDENUM,FELT,IQCEVENTDATAQUALITY,IQCTIMESHIFT,IQCFULLPELLETCOUNT,SINSTFIN,SINSTDET,TDETECT,DRESPMAGTHRESH]
%   = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [EVENTCODE,TDETECTLATENCY,TORIGINPDE,MAGPDE,DLATPDE,DLONPDE,DDEPTHPDE,IUSEDPHFINAL,TORIGININITIAL,MAGINITIAL,DLATINITIAL,DLONINITIAL,DDEPTHINITIAL,DERRMAXHKM,DERRMAXZKM,SCHEDULED_ANALYST,ANALYST1STCLAIM,T1STCLAIMED,ANALYSTLASTCLAIM,TLASTUNCLAIM,ANALYSTFIRSTPUB,QUICK,TFIRSTPUB,ANALYST2NDPUB,Q2UIC,TSECONDPUB,SINSTFIR,TFIRSTEXTP,TFIRSTATWC,TFIRSTPTWC,TFIRSTATWCINT,TFIRSTPTWCINT,INSHA,TBECAMERESP,EVENT_DATE_TIME,PREFMAGCURRENT,DLATCURRENT,DLONCURRENT,DDEPTHCURRENT,TORIGINCURRENT,IUSEDPHCURRENT,TFIRSTGLASS,TORIGINFIRST,MAGFIRST,DLATFIRST,DLONFIRST,DDEPTHFIRST,TORIGINAUTO,MAGAUTO,DLATAUTO,DLONAUTO,DDEPTHAUTO,TORIGIN10,MAG10,DLAT10,DLON10,DDEPTH10,IPDENUM,FELT,IQCEVENTDATAQUALITY,IQCTIMESHIFT,IQCFULLPELLETCOUNT,SINSTFIN,SINSTDET,TDETECT,DRESPMAGTHRESH]
%   = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [EVENTCODE,TDETECTLATENCY,TORIGINPDE,MAGPDE,DLATPDE,DLONPDE,DDEPTHPDE,IUSEDPHFINAL,TORIGININITIAL,MAGINITIAL,DLATINITIAL,DLONINITIAL,DDEPTHINITIAL,DERRMAXHKM,DERRMAXZKM,SCHEDULED_ANALYST,ANALYST1STCLAIM,T1STCLAIMED,ANALYSTLASTCLAIM,TLASTUNCLAIM,ANALYSTFIRSTPUB,QUICK,TFIRSTPUB,ANALYST2NDPUB,Q2UIC,TSECONDPUB,SINSTFIR,TFIRSTEXTP,TFIRSTATWC,TFIRSTPTWC,TFIRSTATWCINT,TFIRSTPTWCINT,INSHA,TBECAMERESP,EVENT_DATE_TIME,PREFMAGCURRENT,DLATCURRENT,DLONCURRENT,DDEPTHCURRENT,TORIGINCURRENT,IUSEDPHCURRENT,TFIRSTGLASS,TORIGINFIRST,MAGFIRST,DLATFIRST,DLONFIRST,DDEPTHFIRST,TORIGINAUTO,MAGAUTO,DLATAUTO,DLONAUTO,DDEPTHAUTO,TORIGIN10,MAG10,DLAT10,DLON10,DDEPTH10,iPDENum,Felt,iQCEventDataQuality,iQCTimeShift,iQCFullPelletCount,SINSTFIN,SINSTDET,tDetect,dRespMagThresh] = importfile('NEIC_QC_2015_2016.csv',2, 32649);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2016/07/18 08:11:14

%% Initialize variables.
delimiter = ',';
startRow = 2;
endRow = inf;

%% Format string for each line of text:
%   column1: EventCode (%s)
%	column2: Detection Latency (%f)
%   column3: PDE Origin Time (%f)
%	column4: PDE Magnitude (%f)
%   column5: PDE Latitude (%f)
%	column6: PDE Longitude (%f)
%   column7: PDE Depth (%f)
%	column8: PDE Phase Count (%s)
%   column9: Initial NEIC Origin Time (%f)
%	column10: Initial NEIC Magnitude (%f)
%   column11: Initial NEIC Latitude (%f)
%	column12: Initital NEIC Longitude (%f)
%   column13: Initial NEIC Depth (%f)
%	column14: Initial NEIC max horizontal error (%f)
%   column15: Initial NEIC mac vertical error (%f)
%	column16: Scheduled Analyst (%s)
%   column17: Analyst that first claimed event (%f)
%	column18: First Claim Time (%f)
%   column19: Last Claim Time (%f)
%	column20: Time last unclaimed (%f)
%   column21: Analyst that first released the event (%f)
%	column22: TRUE/FALSE If was quick review (%s)
%   column23: Time of first publically released (%f)
%	column24: Analyst of 2nd Release (%f)
%   column25: TRUE/FALSE Quick Review (%s)
%	column26: Time for 2nd public release (%f)
%   column27: Center ID For first release (%s)
%	column28: Time of First Release (%f)
%   column29: Time first ATWC PUBLIC publication (%f)
%	column30: Time first PTWC PUBLIC publication (%f)
%   column31: Time first ATWC Internal publication (%f)
%	column32: Time first PTWC Internal publication (%f)
%   column33: Shadow (%s)
%	column34: Time that this quake first reached resp threshold (theoretical) (%f)
%   column35: Preferred DATETIME Stamp of Event (%s)
%	column36: Preferred Magnitude (%f)
%   column37: Preferred Latitude (%f)
%	column38: Preferred Longitude (%f)
%   column39: Preferred Depth (%f)
%	column40: Preferred Origin Time (%f)
%   column41: Preferred Number of phases used (%f)
%	column42: Time for First GLASS Detection (%f)
%   column43: Initial Origin Time (%f)
%	column44: Initial Magnitude (%f)
%   column45: Initial Latitude (%f)
%	column46: Initial Longitude (%f)
%   column47: Initital Depth (%f)
%	column48: Automatic Origin Time (%f)
%   column49: Automatic Magnitude (%f)
%	column50: Automatic Latitude (%f)
%   column51: Automatic Longitude (%f)
%	column52: Automatic Depth (%f)
%   column53: Final Processing Origin Time (%f)
%	column54: Final Processing Magnitude (%f)
%   column55: Final Processing Latitude (%s)
%	column56: Final Processing Longitude (%s)
%   column57: Final Processing Depth (%s)
%	column58: Verified PDE in which event appeared (%f)
%   column59: Event Felt? (1/0) (%f)
%	column60: iQCEventData Quality (%f)
%   column61: iQCTimeShift (%f)
%	column62: iQCFullPelletCount (%f)
%   column63: sInstFinal Origin (%s)
%	column64: NEIC installation that first detected/reported the event (%s)
%   column65: Detection Time Associated with sInstDetect (%f)
%	column66: Magnitude threshold (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%f%f%f%f%f%f%f%f%f%f%f%f%f%f%s%f%f%f%f%f%s%f%f%s%f%s%f%f%f%f%f%s%f%s%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%s%s%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
%EVENTCODE = dataArray{:, 1};
TDETECTLATENCY = dataArray{:, 2};
TORIGINPDE = dataArray{:, 3};
MAGPDE = dataArray{:, 4};
DLATPDE = dataArray{:, 5};
DLONPDE = dataArray{:, 6};
DDEPTHPDE = dataArray{:, 7};
%IUSEDPHFINAL = dataArray{:, 8};
TORIGININITIAL = dataArray{:, 9};
MAGINITIAL = dataArray{:, 10};
DLATINITIAL = dataArray{:, 11};
DLONINITIAL = dataArray{:, 12};
DDEPTHINITIAL = dataArray{:, 13};
%DERRMAXHKM = dataArray{:, 14};
%DERRMAXZKM = dataArray{:, 15};
%SCHEDULED_ANALYST = dataArray{:, 16};
%ANALYST1STCLAIM = dataArray{:, 17};
%T1STCLAIMED = dataArray{:, 18};
%ANALYSTLASTCLAIM = dataArray{:, 19};
%TLASTUNCLAIM = dataArray{:, 20};
%ANALYSTFIRSTPUB = dataArray{:, 21};
%QUICK = dataArray{:, 22};
TFIRSTPUB = dataArray{:, 23};
%ANALYST2NDPUB = dataArray{:, 24};
% Q2UIC = dataArray{:, 25};
% TSECONDPUB = dataArray{:, 26};
SINSTFIR = dataArray{:, 27};
TFIRSTEXTP = dataArray{:, 28};
% TFIRSTATWC = dataArray{:, 29};
% TFIRSTPTWC = dataArray{:, 30};
TFIRSTATWCINT = dataArray{:, 31};
TFIRSTPTWCINT = dataArray{:, 32};
% INSHA = dataArray{:, 33};
% TBECAMERESP = dataArray{:, 34};
EVENT_DATE_TIME = dataArray{:, 35};
EVENT_DATE_TIME = datenum(EVENT_DATE_TIME,'yyyy/mm/dd HH:MM:SS');
PREFMAGCURRENT = dataArray{:, 36};
DLATCURRENT = dataArray{:, 37};
DLONCURRENT = dataArray{:, 38};
DDEPTHCURRENT = dataArray{:, 39};
% TORIGINCURRENT = dataArray{:, 40};
% IUSEDPHCURRENT = dataArray{:, 41};
% TFIRSTGLASS = dataArray{:, 42};
% TORIGINFIRST = dataArray{:, 43};
% MAGFIRST = dataArray{:, 44};
% DLATFIRST = dataArray{:, 45};
% DLONFIRST = dataArray{:, 46};
% DDEPTHFIRST = dataArray{:, 47};
% TORIGINAUTO = dataArray{:, 48};
% MAGAUTO = dataArray{:, 49};
% DLATAUTO = dataArray{:, 50};
% DLONAUTO = dataArray{:, 51};
% DDEPTHAUTO = dataArray{:, 52};
% TORIGIN10 = dataArray{:, 53};
% MAG10 = dataArray{:, 54};
% DLAT10 = dataArray{:, 55};
% DLON10 = dataArray{:, 56};
% DDEPTH10 = dataArray{:, 57};
% iPDENum = dataArray{:, 58};
% Felt = dataArray{:, 59};
% iQCEventDataQuality = dataArray{:, 60};
% iQCTimeShift = dataArray{:, 61};
% iQCFullPelletCount = dataArray{:, 62};
% SINSTFIN = dataArray{:, 63};
SINSTDET = dataArray{:, 64};
% tDetect = dataArray{:, 65};
% dRespMagThresh = dataArray{:, 66};
%
% For now, just save the important information
%
Data.data = [EVENT_DATE_TIME,PREFMAGCURRENT,DLATCURRENT,DLONCURRENT,DDEPTHCURRENT];
Data.HypoProg = [TORIGINPDE,MAGPDE,DLATPDE,DLONPDE,DDEPTHPDE,TORIGININITIAL,MAGINITIAL,DLATINITIAL,DLONINITIAL,DDEPTHINITIAL];
Data.sINST = cell(length(SINSTDET),6);
for ii = 1 : length(Data.sINST)
    Data.sINST{ii,1} = SINSTFIR{ii,:};
    Data.sINST{ii,2} = TFIRSTEXTP(ii);
    Data.sINST{ii,3} = TFIRSTATWCINT(ii);
    Data.sINST{ii,4} = TFIRSTPTWCINT(ii);
    Data.sINST{ii,5} = TDETECTLATENCY(ii);
    Data.sINST{ii,6} = TFIRSTPUB(ii);
end

end


